"""Render a CaseRun as a Markdown document set."""

from collections import Counter
from datetime import datetime

from battle_test import grounding
from battle_test.citations import PLACEHOLDER
from battle_test.pipeline import CaseRun, Document

DISCLAIMER = (
    "> **Draft for attorney review — not legal advice.** Generated by "
    "adversarial language models to stress-test a position. No winner is "
    "declared. Statute, rule and constitution citations have been checked "
    "against a local copy of the law, but only for whether they exist and are "
    "in force, not for whether they say what the brief claims. Case law has "
    "**not** been checked. Every `[CITATION NEEDED: …]` placeholder and ⚠ mark "
    "needs attention before any of this is relied on."
)

_STATUS_LABELS = {
    grounding.VERIFIED: "✅ in force",
    grounding.IN_FORCE_NOT_PROVIDED: "☑ in force, but the model never saw its text",
    grounding.AMBIGUOUS: "⚠ ambiguous (matches more than one section)",
    grounding.NOT_IN_FORCE: "❌ not in force",
    grounding.NOT_FOUND: "❌ not found",
    grounding.WRONG_JURISDICTION: "❌ other state's law",
}


def render_markdown(run: CaseRun, generated_at: datetime) -> str:
    meta = run.law_meta
    lines = [
        f"# Battle test — {run.state}",
        "",
        DISCLAIMER,
        "",
        f"- **Jurisdiction:** {run.state} and federal law",
        f"- **Law checked against:** statutes, court rules and constitutions current as of "
        f"{meta.get('snapshot_date', '?')} ({meta.get('attribution', 'Open US Law')}, "
        f"snapshot {meta.get('snapshot', '?')})",
        f"- **Generated:** {generated_at:%Y-%m-%d %H:%M}",
        f"- **Rounds:** {run.rounds}",
        f"- **Plaintiff model:** `{run.plaintiff_model}`",
        f"- **Defendant model:** `{run.defendant_model}`",
    ]
    lines += _citation_summary(run)
    for doc in run.documents:
        source = "LLM-generated" if doc.generated else "user-supplied"
        lines += ["", "---", "", f"## {doc.title}", "", f"*{doc.role.title()} · {source}*", "", doc.text]
    lines += _appendix(run)
    return "\n".join(lines) + "\n"


def _citation_summary(run: CaseRun) -> list[str]:
    lines = [
        "", "## Citation check", "",
        "| Document | ✅ in force | ☑ in force, not shown to model | ❌ problems "
        "| ⚠ ambiguous | unchecked lines | `[CITATION NEEDED]` |",
        "|---|---|---|---|---|---|---|",
    ]
    for doc in run.documents:
        counts = Counter(c.status for c in doc.checks)
        problems = sum(counts[s] for s in grounding.PROBLEM_STATUSES)
        placeholders = sum(1 for m in PLACEHOLDER.finditer(doc.text) if m.group().startswith("[CITATION"))
        lines.append(
            f"| {doc.title} | {counts[grounding.VERIFIED]} | {counts[grounding.IN_FORCE_NOT_PROVIDED]} "
            f"| {problems} | {counts[grounding.AMBIGUOUS]} | {len(doc.unchecked)} | {placeholders} |"
        )
    for doc in run.documents:
        lines += _document_details(doc)
    return lines


def _document_details(doc: Document) -> list[str]:
    notable = [c for c in doc.checks if c.status != grounding.VERIFIED]
    if not notable and not doc.unchecked:
        return []
    lines = ["", f"**{doc.title}**", ""]
    for c in notable:
        matched = f" → `{c.section.citation}`" if c.section else ""
        lines.append(f"- {_STATUS_LABELS[c.status]}: `{c.text}`{matched}")
    for snippet in doc.unchecked:
        lines.append(f"- ⚠ not checked (case law, or a format the checker can't read): {snippet}")
    return lines


def _appendix(run: CaseRun) -> list[str]:
    lines = ["", "---", "", "## Appendix: authorities and research", ""]
    for role, queries in run.research.items():
        lines.append(f"**{role.title()} research queries:** " + "; ".join(f"“{q}”" for q in queries))
        lines.append("")
    seen: dict[str, list[str]] = {}
    sections = {}
    for doc in run.documents:
        for s in doc.authorities:
            seen.setdefault(s.citation, []).append(doc.title)
            sections[s.citation] = s
    if seen:
        lines += ["**Authorities quoted to the models:**", ""]
        for citation, titles in seen.items():
            s = sections[citation]
            link = f" — [source]({s.source_url})" if s.source_url else " — ⚠ no official source URL"
            lines.append(f"- `{citation}` {s.section_title}{link}  \n  *given for: {', '.join(titles)}*")
    return lines
