"""Render a CaseRun as a Markdown document set."""

from datetime import datetime

from battle_test.pipeline import CaseRun

DISCLAIMER = (
    "> **Draft for attorney review — not legal advice.** Generated by "
    "adversarial language models to stress-test a position. No winner is "
    "declared. Law grounding is not implemented yet: every "
    "`[CITATION NEEDED: …]` placeholder must be filled with verified, current "
    "authority before any of this is relied on."
)


def render_markdown(run: CaseRun, generated_at: datetime) -> str:
    lines = [
        f"# Battle test — {run.state}",
        "",
        DISCLAIMER,
        "",
        f"- **Jurisdiction:** {run.state} and federal law",
        f"- **Generated:** {generated_at:%Y-%m-%d %H:%M}",
        f"- **Rounds:** {run.rounds}",
        f"- **Plaintiff model:** `{run.plaintiff_model}`",
        f"- **Defendant model:** `{run.defendant_model}`",
    ]
    for doc in run.documents:
        source = "LLM-generated" if doc.generated else "user-supplied"
        lines += ["", "---", "", f"## {doc.title}", "", f"*{doc.role.title()} · {source}*", "", doc.text]
    return "\n".join(lines) + "\n"
